const TAG = window.__GRAV_FIELD_TAG;

if (!window.__seomagicPageDataFetch) {
    const cache = new Map();
    window.__seomagicPageDataFetch = (baseUrl, route, lang, headers) => {
        const key = `${route}|${lang || ''}`;
        if (!cache.has(key)) {
            const promise = fetch(`${baseUrl}/seo-magic/page-data/${route}?lang=${lang || ''}`, { headers })
                .then(res => {
                    if (!res.ok) throw new Error(`HTTP ${res.status}`);
                    return res.json();
                })
                .catch(err => { cache.delete(key); throw err; });
            cache.set(key, promise);
        }
        return cache.get(key);
    };
}

class SeomagicTitle extends HTMLElement {
    _field = null;
    _value = '';
    _pageData = null;
    _loading = false;
    _suggesting = false;
    _aiError = null;
    _aiHidden = false;

    set field(v) {
        this._field = v;
        this._render();
    }

    get field() {
        return this._field;
    }

    set value(v) {
        this._value = (typeof v === 'string') ? v : '';
        this._render();
    }

    get value() {
        return this._value;
    }

    connectedCallback() {
        this._render();
        this._fetchPageData();
    }

    _getApiConfig() {
        const baseUrl = window.__GRAV_API_SERVER_URL + (window.__GRAV_API_PREFIX || '/api/v1');
        const token = window.__GRAV_API_TOKEN;
        const headers = { 'Content-Type': 'application/json' };
        if (token) headers['X-API-Token'] = token;
        return { baseUrl, headers };
    }

    _getPageRoute() {
        const match = window.location.pathname.match(/\/pages\/edit\/(.+)/);
        return match ? match[1] : '';
    }

    _getContentLang() {
        // Admin-next exposes the active language on window for custom fields.
        // Avoids reaching into admin-next's site-scoped localStorage, which
        // is not resolvable from here on sub-path installs.
        return window.__GRAV_CONTENT_LANG || '';
    }


    _getSource() {
        return this._field?.source || 'generated';
    }

    async _fetchPageData() {
        this._loading = true;
        this._render();

        const { baseUrl, headers } = this._getApiConfig();
        const route = this._getPageRoute();

        try {
            const json = await window.__seomagicPageDataFetch(baseUrl, route, this._getContentLang(), headers);
            this._pageData = json.data;
        } catch (e) {
            this._pageData = null;
        }

        this._loading = false;
        this._render();
    }

    _getAutoGeneratedTitle() {
        if (!this._pageData) return null;

        const source = this._getSource();

        if (source === 'generated') {
            return this._pageData.rawdata?.head?.title || this._pageData.page_title || null;
        }

        if (source === 'metadata' || source === 'opengraph') {
            const meta = this._pageData.metadata;
            if (source === 'metadata' && meta?.['og:title']) {
                return meta['og:title'];
            }
            if (source === 'opengraph' && meta?.['twitter:title']) {
                return meta['twitter:title'];
            }
            return null;
        }

        return null;
    }

    _getAutoGeneratedLabel() {
        const source = this._getSource();
        const autoTitle = this._getAutoGeneratedTitle();

        if (source === 'generated') {
            return autoTitle || 'No auto-generated title available';
        }

        if (source === 'metadata') {
            return autoTitle || 'Falls back to SEO title';
        }

        if (source === 'opengraph') {
            return autoTitle || 'Falls back to SEO title';
        }

        return 'No auto-generated title available';
    }

    _onInput(e) {
        this._value = e.target.value;
        this._updateCounter();
        this.dispatchEvent(new CustomEvent('change', { detail: this._value }));
    }

    _updateCounter() {
        const counter = this.querySelector('[data-counter]');
        if (!counter) return;
        const len = (this._value || '').length;
        counter.textContent = `${len} chars`;
        counter.style.color = len > 60 ? '#ef4444' : 'var(--muted-foreground, #71717a)';
    }

    async _suggest() {
        if (this._suggesting) return;

        this._suggesting = true;
        this._aiError = null;
        this._render();

        const { baseUrl, headers } = this._getApiConfig();
        const route = this._getPageRoute();

        try {
            const title = this._pageData?.page_title || '';
            const body = this._pageData?.body || '';
            const prompt = `Generate a concise, SEO-friendly page title (≤ 60 characters).\nOutput ONLY the title, no quotes or extra text.\n\n${title ? 'Existing title: ' + title + '\n\n' : ''}Page content:\n${body.substring(0, 4000)}`;

            const res = await fetch(`${baseUrl}/ai-pro/chat`, {
                method: 'POST',
                headers,
                body: JSON.stringify({
                    provider: '',
                    prompt: prompt,
                    context: JSON.stringify({ type: 'page', title, content: body.substring(0, 12000) }),
                }),
            });

            if (!res.ok) {
                if (res.status === 404) {
                    this._aiHidden = true;
                    this._suggesting = false;
                    this._render();
                    return;
                }
                throw new Error(`HTTP ${res.status}`);
            }

            const json = await res.json();
            const data = json.data || json;
            let suggestion = data.response || data.content || '';
            if (typeof suggestion === 'object' && suggestion.content) suggestion = suggestion.content;

            if (suggestion) {
                this._value = suggestion;
                this.dispatchEvent(new CustomEvent('change', { detail: this._value }));
            }
        } catch (e) {
            this._aiError = e.message;
        }

        this._suggesting = false;
        this._render();
    }

    _render() {
        const charCount = (this._value || '').length;
        const charColor = charCount > 60 ? '#ef4444' : 'var(--muted-foreground, #71717a)';
        const autoLabel = this._getAutoGeneratedLabel();

        const spinnerSvg = `
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="animation: seomagic-title-spin 1s linear infinite;">
                <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
            </svg>
        `;

        const aiButtonHtml = this._aiHidden ? '' : `
            <button
                data-ai-btn
                ${this._suggesting ? 'disabled' : ''}
                style="
                    display: inline-flex;
                    align-items: center;
                    gap: 5px;
                    padding: 6px 14px;
                    border-radius: 6px;
                    border: none;
                    background: linear-gradient(135deg, #8b5cf6, #6d28d9);
                    color: #fff;
                    font-size: 12px;
                    font-weight: 600;
                    cursor: ${this._suggesting ? 'not-allowed' : 'pointer'};
                    opacity: ${this._suggesting ? '0.7' : '1'};
                    transition: opacity 0.15s ease;
                    font-family: inherit;
                    white-space: nowrap;
                    flex-shrink: 0;
                "
            >
                ${this._suggesting ? spinnerSvg : `
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m12 3-1.9 5.8a2 2 0 0 1-1.287 1.288L3 12l5.8 1.9a2 2 0 0 1 1.288 1.287L12 21l1.9-5.8a2 2 0 0 1 1.287-1.288L21 12l-5.8-1.9a2 2 0 0 1-1.288-1.287Z"/>
                    </svg>
                `}
                ${this._suggesting ? 'Suggesting...' : 'AI: Suggest Title'}
            </button>
        `;

        const aiErrorHtml = this._aiError ? `
            <div style="
                margin-top: 6px;
                padding: 6px 10px;
                border-radius: 6px;
                background: color-mix(in srgb, var(--destructive, #ef4444) 12%, transparent);
                color: var(--destructive, #ef4444);
                font-size: 12px;
                line-height: 1.4;
            ">AI suggestion failed: ${this._aiError}</div>
        ` : '';

        const loadingPlaceholder = this._loading ? `
            <div style="
                display: flex;
                align-items: center;
                gap: 6px;
                margin-top: 8px;
                padding: 8px 12px;
                background: #eff6ff;
                border-left: 3px solid #3b82f6;
                border-radius: 0 6px 6px 0;
                font-size: 13px;
                color: var(--muted-foreground, #71717a);
            ">
                ${spinnerSvg}
                Loading auto-generated title...
            </div>
        ` : `
            <div style="
                margin-top: 8px;
                padding: 8px 12px;
                background: color-mix(in srgb, var(--primary, #3b82f6) 10%, var(--background, #fff));
                border-left: 3px solid var(--primary, #3b82f6);
                border-radius: 0 6px 6px 0;
                font-size: 13px;
                line-height: 1.5;
                color: var(--foreground, #18181b);
            ">
                <div style="font-weight: 500; color: var(--muted-foreground, #71717a); font-size: 12px;">Auto-Generated:</div>
                <div style="margin-top: 2px; font-weight: 600; color: var(--primary, #2563eb);">${this._escapeHtml(autoLabel)}</div>
            </div>
        `;

        this.innerHTML = `
            <style>
                @keyframes seomagic-title-spin {
                    from { transform: rotate(0deg); }
                    to { transform: rotate(360deg); }
                }
            </style>
            <div style="display: flex; flex-direction: column;">
                <div style="position: relative;">
                    <input
                        data-input
                        type="text"
                        value="${this._escapeAttr(this._value || '')}"
                        placeholder="Enter custom SEO title..."
                        style="
                            width: 100%;
                            padding: 8px 12px;
                            padding-right: 80px;
                            border: 1px solid var(--border, #e4e4e7);
                            border-radius: 6px;
                            font-size: 14px;
                            font-family: inherit;
                            color: var(--foreground, #18181b);
                            background: var(--background, #fff);
                            outline: none;
                            box-sizing: border-box;
                            transition: border-color 0.15s ease;
                        "
                    />
                    <span
                        data-counter
                        style="
                            position: absolute;
                            right: 10px;
                            top: 50%;
                            transform: translateY(-50%);
                            font-size: 12px;
                            color: ${charColor};
                            pointer-events: none;
                            white-space: nowrap;
                        "
                    >${charCount} chars</span>
                </div>
                ${loadingPlaceholder}
                ${aiButtonHtml ? `<div style="margin-top: 6px; display: flex; align-items: center; gap: 10px;">${aiButtonHtml}<span style="font-size: 12px; color: var(--muted-foreground, #71717a);">Uses AI-Pro default provider to suggest an SEO title (\u2264 60 chars)</span></div>` : ''}
                ${aiErrorHtml}
            </div>
        `;

        const input = this.querySelector('[data-input]');
        if (input) {
            input.addEventListener('input', (e) => this._onInput(e));
            input.addEventListener('focus', () => {
                input.style.borderColor = 'var(--ring, #3b82f6)';
            });
            input.addEventListener('blur', () => {
                input.style.borderColor = 'var(--border, #e4e4e7)';
            });
        }

        const aiBtn = this.querySelector('[data-ai-btn]');
        if (aiBtn) {
            aiBtn.addEventListener('click', () => this._suggest());
        }
    }

    _escapeHtml(str) {
        const div = document.createElement('div');
        div.textContent = str;
        return div.innerHTML;
    }

    _escapeAttr(str) {
        if (typeof str !== 'string') str = str == null ? '' : String(str);
        return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }
}

customElements.define(TAG, SeomagicTitle);
